import pandas as pd

try:
    # Load the dataset
    orders = pd.read_excel('orders.xlsx', engine='openpyxl')
except Exception as e:
    print("Error while reading the data: ", str(e))
    exit()

# Convert order_date to pandas datetime format
try:
    orders['order_date'] = pd.to_datetime(orders['order_date'], format='%Y-%m-%d')
except Exception as e:
    print("Error while parsing the date: ", str(e))
    exit()

# Compute total cost for each order and store it as a new column
try:
    orders['total_cost'] = orders['quantity'] * orders['product_price']
except Exception as e:
    print("Error while calculating total cost: ", str(e))
    exit()

# Compute the total revenue generated by the online store for each month
monthly_revenue = orders.groupby(orders['order_date'].dt.to_period('M')).sum()['total_cost']

# Compute the total revenue generated by each product
product_revenue = orders.groupby('product_name').sum()['total_cost']

# Compute the total revenue generated by each customer
customer_revenue = orders.groupby('customer_id').sum()['total_cost']

# Identify the top 10 customers by revenue generated
top_customers = customer_revenue.nlargest(10)

# Print aggregated data
print("Monthly Revenue:\n", monthly_revenue)
print("\nProduct Revenue:\n", product_revenue)
print("\nCustomer Revenue:\n", customer_revenue)
print("\nTop 10 Customers:\n", top_customers)
